import { useEffect, useRef, useState } from 'react'
import { ChevronLeft, Star, AlertTriangle, ClipboardCheck } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import {
  fetchMatch, fetchTeamLineup, subscribeMatch,
  fetchMatchByPath, subscribeMatchByPath,
  fetchCompetition, fetchPerson,
  toDate,
} from '../lib/queries'
import { fetchCompetitionTeamSheet, deleteMatch, removeFixtureFromCompetition } from '../lib/adminQueries'
import { resolveSideLineup, isInheritedLineup } from '../lib/lineupResolve'
import { configured } from '../firebase'
import ShareButton from '../components/ShareButton'
import VenueLabel from '../components/VenueLabel'
import StatusBadge from '../components/StatusBadge'
import FixtureBanner from '../components/FixtureBanner'
import { MatchTeamIdentity, MatchTeamCrest } from '../components/TeamIdentity'
import PersonAvatar from '../components/PersonAvatar'
import { playerUrl, matchUrl } from '../lib/slugify'
import { pomForSide, pomColor, pomBgTint, isLineupEntryPOM } from '../lib/pom'
import { teamAccent } from '../lib/teamAccent'
import { gameMinuteLabel, periodRemainingMs, formatCountdown } from '../lib/matchClock'
import { useSeoMeta } from '../lib/useSeoMeta'

const GOAL_TYPE_LABEL = { open: 'Action', pp: 'Power Play', counter: 'Counter', pen: 'Penalty', og: 'Own Goal' }
// Water polo player sanctions (keys shared with the stats engine):
//   green → Exclusion (20s), yellow → Match exclusion, red → Brutality.
const CARD_LABEL      = { green: 'Exclusion', yellow: 'Match exclusion', red: 'Brutality' }
const CARD_COLOR      = { green: '#16a34a', yellow: '#ca8a04', red: '#dc2626' }

// Player attribution is secondary — never surface "Unknown" placeholders.
function cleanName(name) {
  if (!name) return null
  const n = String(name).trim()
  if (!n || n.toLowerCase() === 'unknown' || n.toLowerCase() === 'unknown scorer') return null
  return n
}

function cardDurationText(card) {
  if (card.cardType === 'red')    return 'Brutality — ejected, penalty + 4-minute man-down'
  if (card.cardType === 'yellow') return 'Excluded for the rest of the match'
  return '20-second exclusion'
}

// Match slugs are always "team-name-vs-team-name" format generated by buildMatchSlug().
// Build one unified chronological timeline from goals[], cards[] and controlLog[].
// Everything is merged and sorted by matchTimestamp. Reversed events are hidden.
function buildTimeline(match) {
  const events = []
  let maxSort = 0
  const bump = t => { const n = t ?? 0; if (n > maxSort) maxSort = n; return n }

  const teamColor = side =>
    side === 'home' ? (match.homeTeamColor ?? '#334155') : (match.awayTeamColor ?? '#334155')

  // Resolve a scorer/card player's photo from the denormalised lineup entries.
  // Goals reference a person by personId; cards reference the lineup entry id.
  const lineup = [...(match.homeLineup ?? []), ...(match.awayLineup ?? [])]
  const photoByPerson = {}
  const photoByEntry  = {}
  for (const e of lineup) {
    if (e.personId) photoByPerson[e.personId] = e.photoUrl ?? null
    if (e.id)       photoByEntry[e.id]         = e.photoUrl ?? null
  }

  for (const g of match.goals ?? []) {
    if (g.status === 'reversed') continue
    events.push({
      key:       `goal-${g.id ?? events.length}`,
      type:      'goal',
      sort:      bump(g.matchTimestamp),
      // A submitted result's goals carry no timestamp — the scorer is known but
      // the minute is not. Show the goal with no minute; never fabricate one.
      time:      g.matchTimestamp != null ? gameMinuteLabel(match, g.matchTimestamp) : null,
      side:      g.side,
      primary:   'Goal',
      // Only show a goal type when one was actually assigned — a result entered
      // after the match carries no type, and the system must NOT assume one.
      secondary: g.goalType ? (GOAL_TYPE_LABEL[g.goalType] ?? null) : null,
      player:    cleanName(g.scorerName),
      playerLabel: 'Scorer',
      playerPhoto: g.scorerPersonId ? (photoByPerson[g.scorerPersonId] ?? null) : null,
      assist:      cleanName(g.assistName),
      assistPhoto: g.assistPersonId ? (photoByPerson[g.assistPersonId] ?? null) : null,
      color:     '#1d4ed8', // goals are always blue regardless of team
    })
  }

  for (const c of match.cards ?? []) {
    if (c.status === 'reversed') continue
    events.push({
      key:       `card-${c.id ?? events.length}`,
      type:      'card',
      sort:      bump(c.matchTimestamp != null ? c.matchTimestamp : (c.minute ?? 0)),
      time:      c.matchTimestamp != null ? gameMinuteLabel(match, c.matchTimestamp) : (c.minute != null ? `${c.minute}'` : null),
      side:      c.side,
      primary:   CARD_LABEL[c.cardType] ?? 'Card',
      secondary: cardDurationText(c),
      player:    cleanName(c.playerName),
      playerLabel: 'Player',
      playerPhoto: c.playerPlayerId ? (photoByEntry[c.playerPlayerId] ?? null) : null,
      color:     CARD_COLOR[c.cardType] ?? '#94a3b8',
    })
  }

  for (const entry of match.controlLog ?? []) {
    let label = null
    if (entry.type === 'match_start' || entry.type === 'period_start') {
      label = entry.period ? `${entry.period} starts` : 'Match starts'
    } else if (entry.type === 'period_end') {
      label = entry.period ? `${entry.period} ends` : 'Period ends'
    } else if (entry.type === 'pause') {
      label = 'Paused'
    } else if (entry.type === 'resume') {
      label = 'Resumed'
    } else if (entry.type === 'abandoned') {
      label = 'Match abandoned'
    }
    if (!label) continue
    events.push({
      key:   `ctrl-${entry.type}-${entry.matchTimestamp ?? 0}-${events.length}`,
      type:  'control',
      sort:  bump(entry.matchTimestamp),
      time:  gameMinuteLabel(match, entry.matchTimestamp),
      side:  null,
      label,
      abandoned: entry.type === 'abandoned',
    })
  }

  // Legacy goals from homeScorers/awayScorers when goals[] is absent
  if (!(match.goals?.length) && (match.homeScorers?.length || match.awayScorers?.length)) {
    const addLegacy = (arr, side) => {
      for (const s of arr ?? []) {
        events.push({
          key:       `legacy-${side}-${events.length}`,
          type:      'goal',
          sort:      bump(s.minute ?? 0),
          time:      s.minute != null ? `${s.minute}'` : null,
          side,
          primary:   'Goal',
          secondary: s.isOwnGoal ? 'Own Goal' : null,
          player:    cleanName(s.name),
          playerLabel: 'Scorer',
          color:     '#1d4ed8',
        })
      }
    }
    addLegacy(match.homeScorers, 'home')
    addLegacy(match.awayScorers, 'away')
  }

  const sorted = events.sort((a, b) => a.sort - b.sort)

  // Full time — synthesized at the end for completed matches (no stored entry).
  if (match.status === 'final') {
    sorted.push({
      key:   'ctrl-full-time',
      type:  'control',
      sort:  maxSort + 1,
      time:  null,
      side:  null,
      label: 'Full time',
      emphasis: true,
    })
  }

  return sorted
}

function Spinner() {
  return <div className="flex justify-center py-12"><div className="w-5 h-5 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"/></div>
}

function fmtMatchDate(val) {
  const d = toDate(val)
  if (!d) return 'TBD'
  return d.toLocaleDateString('en-ZA', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
    + ' · '
    + d.toLocaleTimeString('en-ZA', { hour: '2-digit', minute: '2-digit' })
}

// Event content — text block, aligned toward the spine.
function EventContent({ event, align }) {
  return (
    <div className={`min-w-0 ${align === 'right' ? 'text-right' : 'text-left'}`}>
      <div className="text-slate-900 text-sm font-bold leading-tight">{event.primary}</div>
      {event.secondary && (
        <div className="text-[11px] text-slate-500 leading-snug">{event.secondary}</div>
      )}
      {event.player && (
        <div className={`flex items-center gap-1.5 mt-0.5 ${align === 'right' ? 'justify-end' : ''}`}>
          {align === 'right' && (
            <span className="text-[10px] text-slate-400 leading-snug truncate">{event.playerLabel}: {event.player}</span>
          )}
          <PersonAvatar name={event.player} photoUrl={event.playerPhoto} size={18} />
          {align !== 'right' && (
            <span className="text-[10px] text-slate-400 leading-snug truncate">{event.playerLabel}: {event.player}</span>
          )}
        </div>
      )}
      {event.assist && (
        <div className={`flex items-center gap-1.5 mt-0.5 ${align === 'right' ? 'justify-end' : ''}`}>
          {align === 'right' && (
            <span className="text-[10px] text-slate-400 leading-snug truncate">Assist: {event.assist}</span>
          )}
          <PersonAvatar name={event.assist} photoUrl={event.assistPhoto} size={18} />
          {align !== 'right' && (
            <span className="text-[10px] text-slate-400 leading-snug truncate">Assist: {event.assist}</span>
          )}
        </div>
      )}
    </div>
  )
}

// Node on the spine: colored circle + timestamp stacked below it, both centered.
// bg-white masks the spine line behind the node so the dot floats cleanly.
function TimeNode({ time, color }) {
  return (
    <div className="relative z-10 flex flex-col items-center gap-1 bg-white px-2 shrink-0">
      <span className="w-3 h-3 rounded-full border-2 border-white shadow-sm shrink-0"
        style={{ backgroundColor: color ?? '#cbd5e1', boxShadow: `0 0 0 1.5px ${color ?? '#cbd5e1'}33` }} />
      {time && (
        <span className="font-mono text-[10px] font-bold text-slate-400 tabular-nums leading-none whitespace-nowrap">
          {time}
        </span>
      )}
    </div>
  )
}

// Phase marker (period start/end, full time) — full-width centered divider.
// Has a horizontal tick that crosses the spine so it reads as a structural marker.
// The abandoned marker is emphasised in red: everything above it is the frozen,
// stopped attempt; anything below (on replay) is the fresh game.
function PhaseMarker({ event }) {
  const ab = event.abandoned
  return (
    <div className="flex items-center gap-0 py-0.5">
      <div className={`flex-1 h-px ${ab ? 'bg-red-200' : 'bg-slate-100'}`} />
      <div className="relative z-10 bg-white flex flex-col items-center px-4 gap-0.5">
        <div className={`w-5 h-[2px] rounded-full mb-1 ${ab ? 'bg-red-400' : 'bg-slate-300'}`} />
        <span className={`text-[9px] font-bold uppercase tracking-widest whitespace-nowrap leading-none ${
          ab ? 'text-red-600' : event.emphasis ? 'text-slate-800' : 'text-slate-500'
        }`}>
          {event.label}
        </span>
        {event.time && (
          <span className="font-mono text-[9px] text-slate-400 tabular-nums mt-0.5 leading-none">{event.time}</span>
        )}
      </div>
      <div className={`flex-1 h-px ${ab ? 'bg-red-200' : 'bg-slate-100'}`} />
    </div>
  )
}

function TimelineEvent({ event }) {
  if (event.type === 'control') return <PhaseMarker event={event} />

  // Side = team: home events always left, away events always right.
  const isAway = event.side === 'away'
  return (
    <div className="grid grid-cols-[1fr_3.5rem_1fr] items-start">
      <div className="flex justify-end pr-2 pt-0.5">
        {!isAway && <EventContent event={event} align="right" />}
      </div>
      <TimeNode time={event.time} color={event.color} />
      <div className="flex justify-start pl-2 pt-0.5">
        {isAway && <EventContent event={event} align="left" />}
      </div>
    </div>
  )
}

export default function MatchDetail() {
  const { date, slug, child, season, competitionSlug, matchSlug } = useParams()
  const navigate = useNavigate()
  const { canScore, isPlatformAdmin, isOrgMember } = useAuth()
  // Type-to-confirm safeguard for match deletion (destructive, irreversible).
  const [deleteOpen,    setDeleteOpen]    = useState(false)
  const [deleteText,    setDeleteText]    = useState('')
  const [deleteBusy,    setDeleteBusy]    = useState(false)
  const [deleteError,   setDeleteError]   = useState('')
  const [match,       setMatch]       = useState(null)
  useSeoMeta({ type: 'match', entity: match })
  const [homePlayers, setHomePlayers] = useState([])
  const [awayPlayers, setAwayPlayers] = useState([])
  const [peopleById,  setPeopleById]  = useState({})   // live person docs for line-up members
  const [derivedLineups, setDerivedLineups] = useState(null) // { home, away } for inherited fixtures
  const [loading,     setLoading]     = useState(true)
  const [, setTick]                   = useState(0)
  const lineupsLoaded = useRef(false)

  // Tick the live clock once a second. The clock value itself is derived from
  // getElapsedMs() (wall-clock based), so this only forces a re-render — it
  // never drifts. Frozen while paused or once the match is no longer live.
  useEffect(() => {
    if (match?.status !== 'live' || match?.pausedAt) return
    const t = setInterval(() => setTick(n => n + 1), 1000)
    return () => clearInterval(t)
  }, [match?.status, match?.pausedAt])

  useEffect(() => {
    const onMatch = m => {
      setMatch(m); setLoading(false)
    }
    setLoading(true)

    // Rebuild the stored canonical path from whichever route matched, then
    // resolve by it. Competition matches are competition-scoped and dateless;
    // standalone matches are dated, and `child` is present only for a group child.
    const path = matchSlug
      ? `/competitions/${season}/${competitionSlug}/match/${matchSlug}`
      : child
        ? `/match/${date}/${slug}/${child}`
        : `/match/${date}/${slug}`
    if (!configured) { fetchMatchByPath(path).then(onMatch); return }
    return subscribeMatchByPath(path, onMatch)
  }, [date, slug, child, season, competitionSlug, matchSlug])

  useEffect(() => {
    if (!match || lineupsLoaded.current) return
    lineupsLoaded.current = true
    Promise.all([fetchTeamLineup(match.homeTeamId), fetchTeamLineup(match.awayTeamId)])
      .then(([h, a]) => { setHomePlayers(h); setAwayPlayers(a) })
  }, [match?.homeTeamId, match?.awayTeamId])

  // Resolve the LIVE person record for every line-up member, so the name (and
  // profile slug) always reflect the one people/{id} document — an admin name
  // fix shows here without rewriting the frozen copies on the match/sheet.
  useEffect(() => {
    const ids = [...new Set([
      ...(match?.homeLineup ?? []).map(e => e.personId),
      ...(match?.awayLineup ?? []).map(e => e.personId),
      ...(derivedLineups?.home ?? []).map(e => e.personId),
      ...(derivedLineups?.away ?? []).map(e => e.personId),
    ].filter(Boolean))]
    if (!ids.length) return
    Promise.all(ids.map(pid => fetchPerson(pid).catch(() => null))).then(list => {
      const map = {}
      list.forEach(p => { if (p) map[p.id] = p })
      setPeopleById(map)
    })
  }, [match?.id, match?.homeLineup, match?.awayLineup, derivedLineups])

  // Derived line-ups for tournament/festival fixtures that have not frozen
  // yet (bulk team sheets brief §4/§9): resolve competition squad − exceptions
  // per side. Re-resolves when exceptions change (the match doc is
  // subscribed). Frozen or legacy fixtures skip this entirely.
  const exceptionsKey = JSON.stringify(match?.exceptions ?? [])
  useEffect(() => {
    if (!match?.competitionId || match.lineupMode === 'frozen') { setDerivedLineups(null); return }
    let cancelled = false
    ;(async () => {
      try {
        const comp = await fetchCompetition(match.competitionId)
        if (!comp || !isInheritedLineup(match, comp.type)) { if (!cancelled) setDerivedLineups(null); return }
        const [homeSheet, awaySheet] = await Promise.all([
          match.homeTeamId ? fetchCompetitionTeamSheet(match.competitionId, match.homeTeamId) : { squad: [] },
          match.awayTeamId ? fetchCompetitionTeamSheet(match.competitionId, match.awayTeamId) : { squad: [] },
        ])
        if (cancelled) return
        if (homeSheet.squad.length === 0 && awaySheet.squad.length === 0) { setDerivedLineups(null); return }
        const exceptions = match.exceptions ?? []
        setDerivedLineups({
          home: homeSheet.squad.length > 0
            ? resolveSideLineup({ squad: homeSheet.squad, exceptions, side: 'home' })
            : (match.homeLineup ?? []),
          away: awaySheet.squad.length > 0
            ? resolveSideLineup({ squad: awaySheet.squad, exceptions, side: 'away' })
            : (match.awayLineup ?? []),
        })
      } catch { if (!cancelled) setDerivedLineups(null) }
    })()
    return () => { cancelled = true }
  }, [match?.id, match?.competitionId, match?.lineupMode, exceptionsKey]) // eslint-disable-line react-hooks/exhaustive-deps

  // Advertise the canonical (clean) URL so search engines and link unfurlers
  // prefer it over any legacy id-based URL the visitor may have arrived through.
  useEffect(() => {
    if (!match) return
    const href = window.location.origin + matchUrl(match)
    let link = document.querySelector('link[rel="canonical"]')
    if (!link) { link = document.createElement('link'); link.rel = 'canonical'; document.head.appendChild(link) }
    link.setAttribute('href', href)
  }, [match])

  if (loading) return <Spinner />
  if (!match) return <div className="px-4 py-12 text-center text-slate-500 text-sm">Match not found.</div>

  const isLive   = match.status === 'live'
  const isPaused = match.status === 'paused'
  const isFinal  = match.status === 'final'
  // §3/§8 presentation flags (driven by data, not new statuses):
  // an untracked live match has no scorer present; a submitted final result
  // has no live timeline and is tagged so the absence is understood.
  const untrackedLive = (isLive || isPaused) && match.tracked !== true
  const submittedResult = isFinal && match.resultSource === 'submitted'
  const hasScore = isLive || isPaused || isFinal
  const homeWon  = isFinal && match.homeScore > match.awayScore
  const awayWon  = isFinal && match.awayScore > match.homeScore

  // Fixture lineups show ONLY the players actually selected for THIS match —
  // the match document's own homeLineup / awayLineup. The team squad
  // (homePlayers / awayPlayers, fetched by teamId) is used purely as a lookup
  // to enrich each entry with a profile slug and captaincy; it is never the
  // display source, so a squad member is not painted onto fixtures they were
  // not picked for. No lineup picked → the section stays empty.
  const buildSelection = (entries, roster) => {
    const byId = new Map((roster ?? []).filter(r => r.personId).map(r => [r.personId, r]))
    return (entries ?? [])
      .map(e => {
        const r = e.personId ? byId.get(e.personId) : null
        const live = e.personId ? peopleById[e.personId] : null   // one people/{id} record
        return {
          id:          e.id,
          personId:    e.personId ?? null,
          personName:  live?.fullName || e.personName || r?.personName || 'Unknown',
          photoUrl:    live?.photoUrl ?? e.photoUrl ?? r?.photoUrl ?? null,
          shirtNumber: e.shirtNumber ?? r?.shirtNumber ?? null,
          personSlug:  live?.slug ?? e.personSlug ?? r?.personSlug ?? null,
          // Captaincy reads from the LINE-UP ENTRY first — that is where the
          // team sheet writes it. The roster is a legacy fallback only; a
          // pasted captain would not appear if this joined the roster first.
          isCaptain:   e.isCaptain ?? r?.isCaptain ?? false,
          // Goalkeeper is read from the player's PROFILE position (people doc),
          // not the match — a keeper is tagged (GK) after their name wherever
          // they are sheeted. 'GK' or 'goalkeeper' both count.
          isGoalkeeper: /^(gk|goal)/i.test(String(live?.position ?? r?.position ?? '').trim()),
          isStarter:   !!e.isStarter,
        }
      })
      .sort((a, b) => (Number(b.isStarter) - Number(a.isStarter)) || ((a.shirtNumber || 99) - (b.shirtNumber || 99)))
  }
  // A tournament/festival fixture that has not frozen yet derives its line-ups
  // from the competition squads (squad − exceptions); frozen and legacy
  // fixtures read their stored arrays exactly as before.
  const homeSelection = buildSelection(derivedLineups?.home ?? match.homeLineup, homePlayers)
  const awaySelection = buildSelection(derivedLineups?.away ?? match.awayLineup, awayPlayers)

  // Running scoreboard clock — counts DOWN within the current period, exactly
  // as the scorer sees it (negative past 00:00). Hidden during the
  // between-period break, when there is no period clock to show.
  const liveClock = (isLive || isPaused) && match.startedAt && match.currentPeriod !== 'break'
    ? formatCountdown(periodRemainingMs(match)) : null

  const homeDisplayName = match.homeOrgName ? `${match.homeOrgName} ${match.homeTeamName}` : (match.homeTeamName ?? '')
  const awayDisplayName = match.awayOrgName ? `${match.awayOrgName} ${match.awayTeamName}` : (match.awayTeamName ?? '')
  const shareData = {
    title: hasScore
      ? `${homeDisplayName} ${match.homeScore}–${match.awayScore} ${awayDisplayName}`
      : `${homeDisplayName} vs ${awayDisplayName}`,
    text: isLive ? `LIVE · ${match.currentPeriod ?? ''} · ${homeDisplayName} ${match.homeScore}–${match.awayScore} ${awayDisplayName}`
      : isFinal ? `Full time · ${homeDisplayName} ${match.homeScore}–${match.awayScore} ${awayDisplayName}`
      : `${homeDisplayName} vs ${awayDisplayName}`,
    url: window.location.origin + matchUrl(match),
  }

  const timeline      = buildTimeline(match)
  const hasTimeline   = timeline.length > 0
  const competitionId = match.competitionId
  // Prefer the clean competition-scoped matches URL when the match carries its
  // competition slug + season; fall back to the legacy id-based route.
  const competitionMatchesUrl = (match.competitionSlug && match.competitionSeason)
    ? `/competitions/${match.competitionSeason}/${match.competitionSlug}/matches`
    : competitionId ? `/competitions/${competitionId}/matches` : null

  // Deleting a match is destructive and irreversible, so it sits behind a
  // type-to-confirm dialog (not a one-click browser confirm). Available to the
  // platform admin and to anyone with match authority over either side; the
  // Firestore rules enforce the same on the server.
  const canDeleteMatch = isPlatformAdmin
    || isOrgMember(match.homeOrgId || '')
    || isOrgMember(match.awayOrgId || '')
  const deleteConfirmed = deleteText.trim().toUpperCase() === 'DELETE'

  function openDeleteDialog() {
    setDeleteText('')
    setDeleteError('')
    setDeleteOpen(true)
  }

  // Performs the delete: removes the match doc, clears its competition
  // fixture-membership (if any), and returns to the match's parent.
  async function confirmDeleteMatch() {
    if (!deleteConfirmed || deleteBusy) return
    setDeleteBusy(true)
    setDeleteError('')
    try {
      await deleteMatch(match.id)
      if (competitionId) await removeFixtureFromCompetition(competitionId, match.id).catch(() => {})
      navigate(competitionMatchesUrl || '/admin/matches')
    } catch (e) {
      setDeleteError(e.message || 'Delete failed.')
      setDeleteBusy(false)
    }
  }

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 pb-12 space-y-4">

      {/* Type-to-confirm delete dialog — deliberate friction before a
          destructive, irreversible action. */}
      {deleteOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"
          onClick={() => !deleteBusy && setDeleteOpen(false)}>
          <div className="bg-white rounded-2xl border border-slate-200 shadow-xl w-full max-w-md p-6 space-y-4"
            onClick={(e) => e.stopPropagation()}>
            <div className="flex items-start gap-3">
              <div className="w-9 h-9 rounded-full bg-red-50 flex items-center justify-center shrink-0">
                <AlertTriangle className="w-5 h-5 text-red-600" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-base">Delete this match?</h3>
                <p className="text-sm text-slate-500 mt-1">
                  {match.homeTeamName || 'Home'} vs {match.awayTeamName || 'Away'} will be permanently
                  removed, along with its score and timeline. This cannot be undone.
                </p>
              </div>
            </div>
            <div>
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-1.5">
                Type <span className="text-red-600">DELETE</span> to confirm
              </label>
              <input
                autoFocus
                type="text"
                value={deleteText}
                onChange={(e) => setDeleteText(e.target.value)}
                disabled={deleteBusy}
                placeholder="DELETE"
                className="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-red-500/40 focus:border-red-400 disabled:bg-slate-50"
              />
            </div>
            {deleteError && (
              <p className="text-sm text-red-600">{deleteError}</p>
            )}
            <div className="flex items-center justify-end gap-2 pt-1">
              <button
                onClick={() => setDeleteOpen(false)}
                disabled={deleteBusy}
                className="text-sm font-bold text-slate-500 hover:text-slate-900 px-3 py-2 rounded-lg transition-colors disabled:opacity-50">
                Cancel
              </button>
              <button
                onClick={confirmDeleteMatch}
                disabled={!deleteConfirmed || deleteBusy}
                className="text-sm font-bold text-white bg-red-600 hover:bg-red-500 px-4 py-2 rounded-lg transition-colors disabled:opacity-40 disabled:cursor-not-allowed">
                {deleteBusy ? 'Deleting…' : 'Delete match'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Back nav */}
      <div className="flex items-center gap-3">
        <button onClick={() => navigate(-1)}
          className="flex items-center gap-2 min-h-[44px] text-slate-400 hover:text-slate-900 transition-colors text-sm font-medium">
          <ChevronLeft className="w-4 h-4" />
          Back
        </button>
        <div className="ml-auto flex items-center gap-3">
          {canScore && !isFinal && (
            <Link to={`/score/${match.id}`}
              className="flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs uppercase tracking-wider rounded-lg px-3 py-2 transition-colors shrink-0">
              {isLive || isPaused ? '● Score' : 'Score'}
            </Link>
          )}
          {isPlatformAdmin && (
            <Link to={`/score/${match.id}`}
              className="flex items-center gap-1.5 border border-slate-300 hover:border-slate-400 text-slate-600 hover:text-slate-900 font-bold text-xs uppercase tracking-wider rounded-lg px-3 py-2 transition-colors shrink-0">
              Edit
            </Link>
          )}
          {/* Match deletion is destructive — gated to delete-authority and
              guarded by the type-to-confirm dialog below. */}
          {canDeleteMatch && (
            <button onClick={openDeleteDialog}
              className="flex items-center gap-1.5 border border-red-200 hover:border-red-300 text-red-600 hover:text-red-700 font-bold text-xs uppercase tracking-wider rounded-lg px-3 py-2 transition-colors shrink-0">
              Delete
            </button>
          )}
          {competitionMatchesUrl && (
            <Link to={competitionMatchesUrl}
              className="text-[11px] font-bold uppercase tracking-widest text-emerald-600 hover:text-emerald-500 transition-colors truncate">
              Matches →
            </Link>
          )}
        </div>
      </div>

      {/* Result card */}
      <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm">

        {/* Team colour identity band — home colour left, away colour right.
            This is a visual team identifier, not a progress/possession indicator. */}
        <div className="flex h-1.5 rounded-t-2xl overflow-hidden">
          <div className="flex-1" style={{ backgroundColor: match.homeTeamColor ?? '#94a3b8' }} />
          <div className="flex-1" style={{ backgroundColor: match.awayTeamColor ?? '#94a3b8' }} />
        </div>

        {/* Status pill */}
        <div className="flex items-center justify-center gap-2 pt-5 pb-0 px-5">
          <StatusBadge status={match.status} />
          {(match.status === 'live' || match.status === 'paused') && match.currentPeriod && (
            <span className="font-mono text-[9px] text-slate-500 uppercase tracking-widest">{match.currentPeriod}</span>
          )}
        </div>

        {/* Outcome banner (walkover / abandoned / not played) — above the score */}
        <div className="px-5 pt-3"><FixtureBanner match={match} /></div>

        {/* Scoreline — crest centered above name on both sides, mirrored */}
        <div className="flex items-start justify-between gap-3 px-5 py-[30px]">

          {/* Home */}
          <div className="flex-1 flex flex-col items-center gap-2 min-w-0">
            <MatchTeamCrest match={match} side="home" size={40} />
            {/* Fixed two-line min-height so both names top-align regardless of wrapping */}
            <div className="min-h-[2.75rem] flex items-start justify-center w-full">
              <MatchTeamIdentity match={match} side="home" align="center" hideIdentifier
                nameClass="font-display font-bold text-sm leading-tight text-center text-slate-900" />
            </div>
          </div>

          {/* Score */}
          <div className="shrink-0 flex flex-col items-center gap-2">
            {hasScore ? (
              <>
                <div className="flex items-center leading-none">
                  <span className="font-mono font-black tabular-nums leading-none text-slate-900"
                    style={{ fontSize: 64 }}>
                    {match.homeScore}
                  </span>
                  <span className="font-mono font-normal text-slate-300 mx-2 leading-none" style={{ fontSize: 40 }}>–</span>
                  <span className="font-mono font-black tabular-nums leading-none text-slate-900"
                    style={{ fontSize: 64 }}>
                    {match.awayScore}
                  </span>
                </div>
                {isFinal && match.shootoutHome != null && match.shootoutAway != null && (
                  <div className="font-mono text-xs text-slate-400 -mt-1">
                    ({match.shootoutHome}–{match.shootoutAway} SO)
                  </div>
                )}
              </>
            ) : (
              <div className="font-mono font-black text-3xl text-slate-400 leading-none">vs</div>
            )}
            {liveClock && (
              <div className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full border ${
                isPaused ? 'bg-amber-50 border-amber-200' : 'bg-red-50 border-red-200'
              }`}>
                <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${isPaused ? 'bg-amber-500' : 'bg-red-500 animate-pulse'}`} />
                <span className={`font-mono text-xs font-bold tabular-nums leading-none ${isPaused ? 'text-amber-600' : 'text-red-600'}`}>
                  {liveClock}
                </span>
              </div>
            )}
          </div>

          {/* Away */}
          <div className="flex-1 flex flex-col items-center gap-2 min-w-0">
            <MatchTeamCrest match={match} side="away" size={40} />
            <div className="min-h-[2.75rem] flex items-start justify-center w-full">
              <MatchTeamIdentity match={match} side="away" align="center" hideIdentifier
                nameClass="font-display font-bold text-sm leading-tight text-center text-slate-900" />
            </div>
          </div>
        </div>

        {/* Meta — date, venue, share */}
        <div className="border-t border-slate-200 px-5 py-5 flex flex-col items-center gap-2 text-center">
          <div className="text-[15px] text-slate-600 leading-snug">{fmtMatchDate(match.scheduledAt)}</div>
          <VenueLabel pitch={match.pitch} venueId={match.venueId} venueSlug={match.venueSlug}
            className="block text-[15px] text-slate-400 leading-snug" />
          <ShareButton shareData={shareData}
            className="mt-1 min-h-[44px] px-6 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 active:bg-slate-100 text-slate-500 hover:text-slate-900 transition-colors shadow-sm" />
        </div>
      </div>

      {/* Live disclaimer — no scorer has started tracking this match (§3). */}
      {untrackedLive && (
        <div className="flex items-start gap-2 bg-amber-50 border border-amber-200 rounded-xl px-4 py-3">
          <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
          <p className="text-xs text-amber-700 leading-relaxed">
            This match may not be being live scored. The scoreline could be out of date until a
            result is confirmed.
          </p>
        </div>
      )}

      {/* Submitted-result tag — a bare result with no minute-by-minute (§8). */}
      {submittedResult && (
        <div className="flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
          <ClipboardCheck className="w-4 h-4 text-slate-400 shrink-0" />
          <p className="text-xs text-slate-500 leading-relaxed">
            Result submitted by an administrator — this match was not live scored, so there is no
            minute-by-minute timeline.
          </p>
        </div>
      )}

      {/* Unified timeline */}
      {hasTimeline && (
        <div className="bg-white rounded-2xl border border-slate-200 px-4 py-5 shadow-sm">
          <div className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-5 text-center">Timeline</div>
          <div className="relative">
            {/* Vertical spine — runs full height, nodes mask it with bg-white */}
            <div className="absolute left-1/2 top-0 bottom-0 w-px bg-slate-200 -translate-x-1/2 pointer-events-none" />
            {/* Fixed 28px gap between every event keeps rhythm locked */}
            <div className="relative flex flex-col gap-7">
              {timeline.map(event => (
                <TimelineEvent key={event.key} event={event} />
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Player of the Match — reads both storage shapes via pomForSide.
          Renders one row if only one side has an award, a two-column grid if
          both. The header colour follows whichever side's award is present
          (matches a competition's chosen POTM colour). */}
      {match.status === 'final' && (() => {
        const homePOTM = pomForSide(match, 'home')
        const awayPOTM = pomForSide(match, 'away')
        if (!homePOTM && !awayPOTM) return null
        const anyPOTM = homePOTM || awayPOTM
        const both    = homePOTM && awayPOTM
        // General fixtures take the awarded (anchor) team's colour; a
        // competition-set POM colour on the record still wins inside pomColor.
        // Every team colour passes through teamAccent (brief §3): contrast
        // and live-red clamps, slate fallback.
        const anchorCol = teamAccent(anyPOTM === homePOTM ? match.homeTeamColor : match.awayTeamColor)
        const items   = [
          homePOTM ? { potm: homePOTM, teamName: match.homeTeamName } : null,
          awayPOTM ? { potm: awayPOTM, teamName: match.awayTeamName } : null,
        ].filter(Boolean)
        return (
          <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
            <div className="flex items-center gap-2 mb-3">
              <Star className="w-4 h-4" style={{ color: pomColor(anyPOTM, anchorCol) }} />
              <div className="text-[10px] font-bold uppercase tracking-widest"
                style={{ color: pomColor(anyPOTM, anchorCol) }}>
                {both ? 'Players of the Match' : 'Player of the Match'}
              </div>
            </div>
            <div className={both ? 'grid grid-cols-2 gap-4' : 'flex'}>
              {items.map(({ potm, teamName }) => (
                <div key={potm.side} className="flex items-center gap-3 min-w-0">
                  <PersonAvatar name={potm.name} photoUrl={potm.photoUrl} size={40} />
                  <div className="min-w-0">
                    <div className="text-slate-900 font-semibold text-sm truncate">{potm.name}</div>
                    <div className="text-[11px] text-slate-500 mt-0.5 truncate">
                      {teamName}
                      {potm.shirtNumber ? ` · #${potm.shirtNumber}` : ''}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )
      })()}

      {/* Lineups — the two teams are laid out as PAIRED ROWS (home[i] beside
          away[i]) in a two-column grid, so a name that wraps to two lines on one
          side reserves the same row height on the other and the lists stay in
          step. Within a row: the cap-number badge sits under the crest (outer
          edge), the name lines up under the org name, and the captain © is packed
          tight against the name on the inner side. Content packs to the outer edge
          of each half, leaving white space down the middle. POTM rows highlight in
          the competition's POM colour (else the team colour, else amber); the cap
          badge renders EMPTY when there is no cap (not a dash, not a zero). */}
      {(homeSelection.length > 0 || awaySelection.length > 0) && (() => {
        const homePOTM = pomForSide(match, 'home')
        const awayPOTM = pomForSide(match, 'away')
        // teamAccent clamps unsafe colours (contrast / live-red) to slate.
        const homeCol  = teamAccent(match.homeTeamColor)
        const awayCol  = teamAccent(match.awayTeamColor)
        const rowCount = Math.max(homeSelection.length, awaySelection.length)
        return (
        <div className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm">
          <div className="text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-4">Lineups</div>
          {/* Team headers */}
          <div className="grid grid-cols-2 gap-x-8 mb-5">
            <div className="flex items-start gap-1.5">
              <MatchTeamCrest match={match} side="home" size={20} />
              <MatchTeamIdentity match={match} side="home" hideIdentifier className="flex-1 min-w-0"
                nameClass="text-xs font-extrabold uppercase tracking-wide text-slate-600 break-words leading-snug" />
            </div>
            <div className="flex items-start gap-1.5 justify-end">
              <MatchTeamIdentity match={match} side="away" hideIdentifier align="right" className="flex-1 min-w-0"
                nameClass="text-xs font-extrabold uppercase tracking-wide text-slate-600 break-words leading-snug" />
              <MatchTeamCrest match={match} side="away" size={20} />
            </div>
          </div>
          {/* Paired player rows */}
          <div className="space-y-2">
            {Array.from({ length: rowCount }).map((_, i) => {
              const h = homeSelection[i]
              const a = awaySelection[i]
              const hPOTM = h ? isLineupEntryPOM(homePOTM, h) : false
              const aPOTM = a ? isLineupEntryPOM(awayPOTM, a) : false
              // (GK) then (C) read as an extension of the name — same styling,
              // so a goalkeeper-captain shows "Name (GK) (C)".
              const hSuffix = h ? `${h.isGoalkeeper ? ' (GK)' : ''}${h.isCaptain ? ' (C)' : ''}` : ''
              const aSuffix = a ? `${a.isGoalkeeper ? ' (GK)' : ''}${a.isCaptain ? ' (C)' : ''}` : ''
              return (
                <div key={i} className="grid grid-cols-2 gap-x-8">
                  {/* Home cell */}
                  {h ? (
                    <div className={`flex items-center gap-1.5 ${hPOTM ? '-mx-2 px-2 py-0.5 rounded' : ''}`}
                      style={hPOTM ? { backgroundColor: pomBgTint(homePOTM, homeCol) } : undefined}>
                      <span className="w-7 h-5 flex items-center justify-center rounded bg-slate-100 border border-slate-200 font-mono tabular-nums text-[10px] font-bold text-slate-500 shrink-0">{h.shirtNumber ?? ''}</span>
                      {h.personId
                        ? <Link to={playerUrl({ id: h.personId, slug: h.personSlug })} className={`text-xs break-words leading-tight min-w-0 hover:text-emerald-600 transition-colors ${hPOTM ? 'font-semibold' : 'text-slate-700'}`} style={hPOTM ? { color: pomColor(homePOTM, homeCol) } : undefined}>{h.personName}{hSuffix}</Link>
                        : <span className={`text-xs break-words leading-tight min-w-0 ${hPOTM ? 'font-semibold' : 'text-slate-700'}`} style={hPOTM ? { color: pomColor(homePOTM, homeCol) } : undefined}>{h.personName}{hSuffix}</span>}
                      {hPOTM && <span className="text-[9px] font-bold uppercase tracking-widest shrink-0" style={{ color: pomColor(homePOTM, homeCol) }}>POTM</span>}
                    </div>
                  ) : <div />}
                  {/* Away cell */}
                  {a ? (
                    <div className={`flex items-center justify-end gap-1.5 ${aPOTM ? '-mx-2 px-2 py-0.5 rounded' : ''}`}
                      style={aPOTM ? { backgroundColor: pomBgTint(awayPOTM, awayCol) } : undefined}>
                      {aPOTM && <span className="text-[9px] font-bold uppercase tracking-widest shrink-0" style={{ color: pomColor(awayPOTM, awayCol) }}>POTM</span>}
                      {a.personId
                        ? <Link to={playerUrl({ id: a.personId, slug: a.personSlug })} className={`text-xs break-words leading-tight min-w-0 text-right hover:text-emerald-600 transition-colors ${aPOTM ? 'font-semibold' : 'text-slate-700'}`} style={aPOTM ? { color: pomColor(awayPOTM, awayCol) } : undefined}>{a.personName}{aSuffix}</Link>
                        : <span className={`text-xs break-words leading-tight min-w-0 text-right ${aPOTM ? 'font-semibold' : 'text-slate-700'}`} style={aPOTM ? { color: pomColor(awayPOTM, awayCol) } : undefined}>{a.personName}{aSuffix}</span>}
                      <span className="w-7 h-5 flex items-center justify-center rounded bg-slate-100 border border-slate-200 font-mono tabular-nums text-[10px] font-bold text-slate-500 shrink-0">{a.shirtNumber ?? ''}</span>
                    </div>
                  ) : <div />}
                </div>
              )
            })}
          </div>
        </div>
        )
      })()}
    </div>
  )
}
